version: '3.8'
services:
  mongo:
    image: mongo:7
    container_name: pizza-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - pizza-mongo-data:/data/db

volumes:
  pizza-mongo-data:
